[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
rpc_url = "${RPC_URL}"
optimizer = true
optimizer_runs = 200

[etherscan]
1924 = { key = "${API_KEY}", url = "https://swell-testnet-explorer.alt.technology/api" }
